version: "3.8"

services:
  frontend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app_network
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

networks:
  app_network: